import type { Locale } from '../types';

export const strings = {
  es: {
    mode: 'Modo',
    input: 'Número de la Seguridad Social',
    placeholder: '28/12345678/40',
    help: 'Uno por línea, hasta 1000. Lo que escribes no se guarda en ningún sitio.',
    result: 'Resultado',
    empty: 'Escribe las 12 cifras, con o sin separadores (28/12345678/40).',
    valid: 'Número válido',
    validOne: '{n} válido',
    validOther: '{n} válidos',
    invalidOne: '{n} no válido',
    invalidOther: '{n} no válidos',
    truncated: 'Solo se comprueban las primeras {n} líneas.',
    province: 'Provincia',
    number: 'Número',
    control: 'Control',
    unknownProvince: 'Provincia no reconocida ({c}). El número puede ser válido igualmente.',
    errControl: 'El control no cuadra: debería ser {e}.',
    errFew: 'Faltan cifras: son 12 (2 de provincia, 8 de número y 2 de control).',
    errMany: 'Sobran cifras: son 12 (2 de provincia, 8 de número y 2 de control).',
    errChars: 'Solo cifras, con espacios, barras o guiones como separadores.',
    provinceLabel: 'Provincia',
    any: 'Cualquiera',
    generated: 'Números generados',
    copyAll: 'Copiar todos',
  },
  en: {
    mode: 'Mode',
    input: 'Social Security number',
    placeholder: '28/12345678/40',
    help: 'One per line, up to 1000. What you type is not stored anywhere.',
    result: 'Result',
    empty: 'Type the 12 digits, with or without separators (28/12345678/40).',
    valid: 'Valid number',
    validOne: '{n} valid',
    validOther: '{n} valid',
    invalidOne: '{n} not valid',
    invalidOther: '{n} not valid',
    truncated: 'Only the first {n} lines are checked.',
    province: 'Province',
    number: 'Number',
    control: 'Control',
    unknownProvince: 'Unknown province ({c}). The number may still be valid.',
    errControl: 'The control digits do not match: they should be {e}.',
    errFew:
      'Digits missing: there are 12 (2 for the province, 8 for the number and 2 for control).',
    errMany:
      'Too many digits: there are 12 (2 for the province, 8 for the number and 2 for control).',
    errChars: 'Digits only, with spaces, slashes or dashes as separators.',
    provinceLabel: 'Province',
    any: 'Any',
    generated: 'Generated numbers',
    copyAll: 'Copy all',
  },
} satisfies Record<Locale, Record<string, string>>;
