import type { Locale } from '../types';

export const strings = {
  es: {
    kind: 'Contenido',
    text: 'Texto',
    textPlaceholder: 'Escribe el texto del código QR',
    url: 'URL',
    urlPlaceholder: 'example.com/pagina',
    urlAdded: 'No tenía esquema: se codifica como {url}',
    badUrl: 'No parece una URL. Escribe algo como example.com o https://example.com/ruta',
    ssid: 'Nombre de la red (SSID)',
    password: 'Contraseña',
    passwordHelp: 'La contraseña no se guarda nunca.',
    security: 'Seguridad',
    wpa: 'WPA/WPA2/WPA3',
    wep: 'WEP',
    nopass: 'Sin contraseña',
    hidden: 'Red oculta',
    ecl: 'Corrección de errores',
    eclL: 'L (7 %)',
    eclM: 'M (15 %)',
    eclQ: 'Q (25 %)',
    eclH: 'H (30 %)',
    size: 'Tamaño del PNG',
    result: 'Código QR',
    ready: '{n}×{n} módulos',
    empty: 'Escribe algo y aquí aparecerá el código QR.',
    alt: 'Código QR de: {text}',
    altWifi: 'Código QR de la red WiFi {ssid}',
    tooLong:
      'El texto no cabe en un QR con corrección {ecl} (máximo {max} bytes; tiene {bytes}). Acórtalo o baja la corrección a L.',
    tooLongL: 'El texto no cabe en un QR (máximo {max} bytes; tiene {bytes}). Acórtalo.',
    png: 'Descargar PNG',
    svg: 'Descargar SVG',
  },
  en: {
    kind: 'Content',
    text: 'Text',
    textPlaceholder: 'Type the text for the QR code',
    url: 'URL',
    urlPlaceholder: 'example.com/page',
    urlAdded: 'It had no scheme: it is encoded as {url}',
    badUrl:
      'That does not look like a URL. Type something like example.com or https://example.com/path',
    ssid: 'Network name (SSID)',
    password: 'Password',
    passwordHelp: 'The password is never saved.',
    security: 'Security',
    wpa: 'WPA/WPA2/WPA3',
    wep: 'WEP',
    nopass: 'No password',
    hidden: 'Hidden network',
    ecl: 'Error correction',
    eclL: 'L (7 %)',
    eclM: 'M (15 %)',
    eclQ: 'Q (25 %)',
    eclH: 'H (30 %)',
    size: 'PNG size',
    result: 'QR code',
    ready: '{n}×{n} modules',
    empty: 'Type something and the QR code will show up here.',
    alt: 'QR code for: {text}',
    altWifi: 'QR code for the WiFi network {ssid}',
    tooLong:
      'The text does not fit in a QR code with {ecl} correction (at most {max} bytes; it has {bytes}). Shorten it or lower the correction to L.',
    tooLongL:
      'The text does not fit in a QR code (at most {max} bytes; it has {bytes}). Shorten it.',
    png: 'Download PNG',
    svg: 'Download SVG',
  },
} satisfies Record<Locale, Record<string, string>>;
