import type { Locale } from '../types';
import type { HolidayKey } from './logic';

export const strings = {
  es: {
    start: 'Fecha de inicio',
    end: 'Fecha de fin',
    includeEnd: 'Incluir el día final',
    result: 'Recuento',
    natural: 'Días naturales',
    weeksOne: '{n} semana',
    weeksOther: '{n} semanas',
    daysOne: '{n} día',
    daysOther: '{n} días',
    weeks: '{weeks} y {days}',
    weekdays: 'Días laborables (L–V)',
    business: 'Días hábiles',
    weekend: 'Días de fin de semana',
    holidays: 'Festivos nacionales en el rango',
    noHolidays: 'No hay festivos nacionales en el rango.',
    onWeekend: 'cae en {d}: no resta',
    summaryOne: '{n} día hábil',
    summaryOther: '{n} días hábiles',
    empty: 'Elige las dos fechas.',
    invalid: 'Escribe fechas válidas, como 2026-01-31.',
    years: 'Elige fechas entre 1900 y 2100.',
    tooLong: 'El rango no puede superar los 100 años.',
    swapped: 'La fecha de fin era anterior a la de inicio: se han intercambiado.',
    note: 'Solo festivos nacionales comunes a toda España. No incluye festivos autonómicos ni locales (como Jueves Santo o San José), ni los traslados que hacen las comunidades cuando un festivo cae en domingo.',
  },
  en: {
    start: 'Start date',
    end: 'End date',
    includeEnd: 'Include the end date',
    result: 'Count',
    natural: 'Calendar days',
    weeksOne: '{n} week',
    weeksOther: '{n} weeks',
    daysOne: '{n} day',
    daysOther: '{n} days',
    weeks: '{weeks} and {days}',
    weekdays: 'Weekdays (Mon–Fri)',
    business: 'Business days',
    weekend: 'Weekend days',
    holidays: 'National holidays in the range',
    noHolidays: 'No national holidays in the range.',
    onWeekend: 'falls on a {d}: not subtracted',
    summaryOne: '{n} business day',
    summaryOther: '{n} business days',
    empty: 'Pick both dates.',
    invalid: 'Type valid dates, like 2026-01-31.',
    years: 'Pick dates between 1900 and 2100.',
    tooLong: 'The range cannot be longer than 100 years.',
    swapped: 'The end date was before the start date: they have been swapped.',
    note: 'Only national holidays shared by all of Spain. Regional and local holidays (such as Maundy Thursday or Saint Joseph’s Day) are not included, nor the holidays regions move when one falls on a Sunday.',
  },
} satisfies Record<Locale, Record<string, string>>;

export const holidayNames: Record<Locale, Record<HolidayKey, string>> = {
  es: {
    newYear: 'Año Nuevo',
    epiphany: 'Epifanía del Señor',
    goodFriday: 'Viernes Santo',
    labour: 'Fiesta del Trabajo',
    assumption: 'Asunción de la Virgen',
    nationalDay: 'Fiesta Nacional de España',
    allSaints: 'Todos los Santos',
    constitution: 'Día de la Constitución',
    immaculate: 'Inmaculada Concepción',
    christmas: 'Navidad',
  },
  en: {
    newYear: 'New Year’s Day',
    epiphany: 'Epiphany',
    goodFriday: 'Good Friday',
    labour: 'Labour Day',
    assumption: 'Assumption of Mary',
    nationalDay: 'National Day of Spain',
    allSaints: 'All Saints’ Day',
    constitution: 'Constitution Day',
    immaculate: 'Immaculate Conception',
    christmas: 'Christmas Day',
  },
};
