import type { Locale } from '../types';

export const strings = {
  es: {
    input: 'Código SWIFT / BIC',
    placeholder: 'CAIXESBBXXX',
    help: 'Uno por línea, hasta 1000.',
    result: 'Resultado',
    empty: 'Escribe un BIC de 8 u 11 caracteres (CAIXESBBXXX).',
    valid: 'BIC válido',
    validOne: '{n} válido',
    validOther: '{n} válidos',
    invalidOne: '{n} no válido',
    invalidOther: '{n} no válidos',
    truncated: 'Solo se comprueban las primeras {n} líneas.',
    bank: 'Banco',
    country: 'País',
    location: 'Localidad',
    branch: 'Sucursal',
    headOffice: 'Oficina principal',
    short: 'Forma de 8',
    long: 'Forma de 11',
    test: 'BIC de pruebas (no operativo).',
    errLength: 'Un BIC tiene 8 u 11 caracteres y este tiene {n}.',
    errBank: 'Los 4 primeros caracteres (el banco) son letras.',
    errCountry: '{c} no es un código de país ISO 3166.',
    errFormat: 'La localidad y la sucursal solo admiten letras y cifras.',
  },
  en: {
    input: 'SWIFT / BIC code',
    placeholder: 'CAIXESBBXXX',
    help: 'One per line, up to 1000.',
    result: 'Result',
    empty: 'Type an 8 or 11 character BIC (CAIXESBBXXX).',
    valid: 'Valid BIC',
    validOne: '{n} valid',
    validOther: '{n} valid',
    invalidOne: '{n} not valid',
    invalidOther: '{n} not valid',
    truncated: 'Only the first {n} lines are checked.',
    bank: 'Bank',
    country: 'Country',
    location: 'Location',
    branch: 'Branch',
    headOffice: 'Head office',
    short: '8-character form',
    long: '11-character form',
    test: 'Test BIC (not live).',
    errLength: 'A BIC has 8 or 11 characters and this one has {n}.',
    errBank: 'The first 4 characters (the bank) are letters.',
    errCountry: '{c} is not an ISO 3166 country code.',
    errFormat: 'Location and branch only take letters and digits.',
  },
} satisfies Record<Locale, Record<string, string>>;
