import type { Locale } from '../types';

export const strings = {
  es: {
    mode: 'Modo',
    warning: 'No son tarjetas reales ni sirven para pagar. Úsalas solo en entornos de prueba.',
    input: 'Número de tarjeta',
    placeholder: '4242 4242 4242 4242',
    help: 'Uno por línea, hasta 1000. Lo que escribes no se guarda en ningún sitio.',
    result: 'Resultado',
    empty: 'Escribe un número de 12 a 19 cifras, con espacios o guiones si quieres.',
    luhnOk: 'Luhn correcto',
    validOne: '{n} válido',
    validOther: '{n} válidos',
    invalidOne: '{n} no válido',
    invalidOther: '{n} no válidos',
    truncated: 'Solo se comprueban las primeras {n} líneas.',
    brand: 'Marca',
    unknownBrand: 'Marca no reconocida',
    number: 'Número',
    length: 'Longitud',
    digits: '{n} cifras',
    unusual: '{brand} con {n} cifras: longitud poco habitual.',
    errLuhn: 'El dígito de control no cuadra: el último debería ser {e}.',
    errLength: 'Una tarjeta tiene entre 12 y 19 cifras y esta tiene {n}.',
    errChars: 'Solo cifras, espacios o guiones.',
    brandLabel: 'Marca',
    expiry: 'Añadir caducidad y CVV',
    seedHelp:
      'Con la misma semilla obtienes siempre el mismo resultado; la caducidad se calcula a partir de la fecha actual, así que puede variar de un mes a otro.',
    generated: 'Tarjetas generadas',
    copyAll: 'Copiar todas',
    stripe: 'Números de prueba de Stripe',
  },
  en: {
    mode: 'Mode',
    warning:
      'These are not real cards and cannot be used to pay. Use them in test environments only.',
    input: 'Card number',
    placeholder: '4242 4242 4242 4242',
    help: 'One per line, up to 1000. What you type is not stored anywhere.',
    result: 'Result',
    empty: 'Type a 12 to 19 digit number, with spaces or dashes if you like.',
    luhnOk: 'Luhn check passed',
    validOne: '{n} valid',
    validOther: '{n} valid',
    invalidOne: '{n} not valid',
    invalidOther: '{n} not valid',
    truncated: 'Only the first {n} lines are checked.',
    brand: 'Brand',
    unknownBrand: 'Unknown brand',
    number: 'Number',
    length: 'Length',
    digits: '{n} digits',
    unusual: '{brand} with {n} digits: unusual length.',
    errLuhn: 'The check digit does not match: the last one should be {e}.',
    errLength: 'A card has 12 to 19 digits and this one has {n}.',
    errChars: 'Digits, spaces or dashes only.',
    brandLabel: 'Brand',
    expiry: 'Add expiry date and CVV',
    seedHelp:
      'The same seed always gives the same result; the expiry date is calculated from the current date, so it can vary from month to month.',
    generated: 'Generated cards',
    copyAll: 'Copy all',
    stripe: 'Stripe test numbers',
  },
} satisfies Record<Locale, Record<string, string>>;
