import type { Locale } from '../types';

export const strings = {
  es: {
    original: 'Original',
    modified: 'Modificado',
    originalPlaceholder: 'Pega aquí el texto original',
    modifiedPlaceholder: 'Pega aquí el texto modificado',
    view: 'Vista',
    unified: 'Unificada',
    split: 'En paralelo',
    ignoreWhitespace: 'Ignorar espacios',
    ignoreCase: 'Ignorar mayúsculas',
    onlyChanges: 'Solo cambios (con contexto)',
    result: 'Diferencias',
    counts: '+{added} añadidas · −{removed} quitadas',
    identical: 'Los textos son iguales',
    empty: 'Pega los dos textos y las diferencias aparecerán aquí.',
    skipped: '{n} líneas iguales',
    tooLarge:
      'Hay demasiadas líneas distintas seguidas para emparejarlas una a una: se muestran como bloque quitado y bloque añadido. Compara fragmentos más pequeños para más detalle.',
    truncated: 'Se muestran las primeras {n} filas. Copia el resultado para verlo entero.',
    added: 'añadida',
    removed: 'quitada',
    swap: 'Intercambiar',
    copyDiff: 'Copiar diff',
  },
  en: {
    original: 'Original',
    modified: 'Modified',
    originalPlaceholder: 'Paste the original text here',
    modifiedPlaceholder: 'Paste the modified text here',
    view: 'View',
    unified: 'Unified',
    split: 'Side by side',
    ignoreWhitespace: 'Ignore spaces',
    ignoreCase: 'Ignore case',
    onlyChanges: 'Changes only (with context)',
    result: 'Differences',
    counts: '+{added} added · −{removed} removed',
    identical: 'The texts are identical',
    empty: 'Paste both texts and the differences will appear here.',
    skipped: '{n} unchanged lines',
    tooLarge:
      'Too many different lines in a row to pair them one by one: they are shown as a removed block and an added block. Compare smaller pieces for more detail.',
    truncated: 'Showing the first {n} rows. Copy the result to see all of it.',
    added: 'added',
    removed: 'removed',
    swap: 'Swap',
    copyDiff: 'Copy diff',
  },
} satisfies Record<Locale, Record<string, string>>;
