import type { Locale } from '../types';

export const strings = {
  es: {
    mode: 'Modo',
    input: 'DNI o NIE',
    placeholder: '12345678Z\nX1234567L',
    notStored: 'Uno por línea, hasta 1000. Lo que escribes no se guarda en ningún sitio.',
    result: 'Resultado',
    empty: 'Escribe un DNI (12345678Z) o un NIE (X1234567L) y se comprueba al momento.',
    validDni: 'DNI válido',
    validNie: 'NIE válido',
    count: '{ok} válidos · {bad} no válidos',
    truncated: 'Solo se comprueban las primeras {n} líneas.',
    kind: 'Tipo',
    dni: 'DNI',
    nie: 'NIE',
    number: 'Número',
    letter: 'Letra',
    padded: 'Tenía 7 cifras: se ha añadido un 0 a la izquierda.',
    wrongLetter: 'Letra incorrecta: para {n} es {l}.',
    forbiddenLetter:
      'La letra {l} no se usa en el DNI. Las posibles son T, R, W, A, G, M, Y, F, P, D, X, B, N, J, Z, S, Q, V, H, L, C, K y E.',
    fewDigits: 'Faltan cifras: un DNI tiene 8 cifras y una letra.',
    manyDigits: 'Sobran cifras: un DNI tiene 8 cifras y una letra.',
    missingLetter: 'Falta la letra: para {n} es {l}.',
    nieDigits: 'Un NIE tiene 7 cifras tras la letra inicial.',
    niePrefix: 'Un NIE empieza por X, Y o Z.',
    cif: 'Los NIF que empiezan por K, L o M se comprueban en el validador de CIF.',
    cifLink: 'Abrir el validador de CIF',
    cifHref: '/es/validador-cif',
    format:
      'Formato no reconocido: un DNI son 8 cifras y una letra (12345678Z) y un NIE, X, Y o Z, 7 cifras y una letra (X1234567L).',
    type: 'Tipo',
    both: 'Ambos',
    dash: 'Con guion (12345678-Z)',
    generated: 'Documentos generados',
    copyAll: 'Copiar todos',
    letterInput: '8 cifras, o X, Y o Z y 7 cifras',
    letterPlaceholder: '12345678',
    letterResult: 'Letra',
    letterEmpty: 'Escribe el número sin la letra y aquí aparece.',
    letterError: 'Escribe 8 cifras (12345678) o X, Y o Z seguida de 7 cifras (X1234567).',
    full: 'Documento completo: {v}',
  },
  en: {
    mode: 'Mode',
    input: 'DNI or NIE',
    placeholder: '12345678Z\nX1234567L',
    notStored: 'One per line, up to 1000. What you type is not stored anywhere.',
    result: 'Result',
    empty: 'Type a DNI (12345678Z) or an NIE (X1234567L) and it is checked right away.',
    validDni: 'Valid DNI',
    validNie: 'Valid NIE',
    count: '{ok} valid · {bad} not valid',
    truncated: 'Only the first {n} lines are checked.',
    kind: 'Type',
    dni: 'DNI',
    nie: 'NIE',
    number: 'Number',
    letter: 'Letter',
    padded: 'It had 7 digits: a leading 0 was added.',
    wrongLetter: 'Wrong letter: for {n} it is {l}.',
    forbiddenLetter:
      'The letter {l} is never used in a DNI. The possible ones are T, R, W, A, G, M, Y, F, P, D, X, B, N, J, Z, S, Q, V, H, L, C, K and E.',
    fewDigits: 'Digits missing: a DNI has 8 digits and a letter.',
    manyDigits: 'Too many digits: a DNI has 8 digits and a letter.',
    missingLetter: 'The letter is missing: for {n} it is {l}.',
    nieDigits: 'An NIE has 7 digits after the first letter.',
    niePrefix: 'An NIE starts with X, Y or Z.',
    cif: 'Tax IDs starting with K, L or M are checked in the CIF validator.',
    cifLink: 'Open the CIF validator',
    cifHref: '/en/spanish-cif-validator',
    format:
      'Unrecognised format: a DNI is 8 digits and a letter (12345678Z) and an NIE is X, Y or Z, 7 digits and a letter (X1234567L).',
    type: 'Type',
    both: 'Both',
    dash: 'With a dash (12345678-Z)',
    generated: 'Generated IDs',
    copyAll: 'Copy all',
    letterInput: '8 digits, or X, Y or Z and 7 digits',
    letterPlaceholder: '12345678',
    letterResult: 'Letter',
    letterEmpty: 'Type the number without its letter and the letter shows up here.',
    letterError: 'Type 8 digits (12345678) or X, Y or Z followed by 7 digits (X1234567).',
    full: 'Full ID: {v}',
  },
} satisfies Record<Locale, Record<string, string>>;
