import type { Locale } from '../types';
import type { PhoneKind } from './logic';

export const strings = {
  es: {
    input: 'Teléfonos',
    placeholder: '+34 612 34 56 78\n(91) 234-56-78',
    help: 'Uno por línea, hasta 1000. Lo que escribes no se guarda en ningún sitio.',
    result: 'Resultado',
    empty: 'Escribe un teléfono de España, con o sin +34, espacios o guiones.',
    validOne: '{n} válido',
    validOther: '{n} válidos',
    invalidOne: '{n} no válido',
    invalidOther: '{n} no válidos',
    truncated: 'Solo se comprueban las primeras {n} líneas.',
    kind: 'Tipo',
    e164: 'E.164',
    national: 'Nacional',
    international: 'Internacional',
    link: 'Enlace',
    call: 'Llamar',
    errForeign: 'Solo números de España (+34).',
    errShort: 'Es un número corto: no tiene formato E.164.',
    errFew: 'Faltan cifras: un teléfono de España tiene 9.',
    errMany: 'Sobran cifras: un teléfono de España tiene 9.',
    errChars: 'Solo cifras, espacios, puntos, guiones, paréntesis y el prefijo +34.',
    errPattern: 'No es un número de España válido: tiene 9 cifras y empieza por 6, 7, 8 o 9.',
    copy: 'Copiar en E.164',
  },
  en: {
    input: 'Phone numbers',
    placeholder: '+34 612 34 56 78\n(91) 234-56-78',
    help: 'One per line, up to 1000. What you type is not stored anywhere.',
    result: 'Result',
    empty: 'Type a Spanish phone number, with or without +34, spaces or dashes.',
    validOne: '{n} valid',
    validOther: '{n} valid',
    invalidOne: '{n} not valid',
    invalidOther: '{n} not valid',
    truncated: 'Only the first {n} lines are checked.',
    kind: 'Type',
    e164: 'E.164',
    national: 'National',
    international: 'International',
    link: 'Link',
    call: 'Call',
    errForeign: 'Spanish numbers only (+34).',
    errShort: 'It is a short number: it has no E.164 form.',
    errFew: 'Digits missing: a Spanish number has 9.',
    errMany: 'Too many digits: a Spanish number has 9.',
    errChars: 'Digits, spaces, dots, dashes, brackets and the +34 prefix only.',
    errPattern: 'Not a valid Spanish number: it has 9 digits and starts with 6, 7, 8 or 9.',
    copy: 'Copy as E.164',
  },
} satisfies Record<Locale, Record<string, string>>;

export const kindNames: Record<Locale, Record<PhoneKind, string>> = {
  es: {
    mobile: 'Móvil',
    personal: 'Número personal',
    freephone: 'Gratuito',
    specialRate: 'Tarifa especial',
    premium: 'Tarificación adicional',
    landline: 'Fijo',
    corporate: 'Red corporativa',
  },
  en: {
    mobile: 'Mobile',
    personal: 'Personal number',
    freephone: 'Freephone',
    specialRate: 'Special rate',
    premium: 'Premium rate',
    landline: 'Landline',
    corporate: 'Corporate network',
  },
};
