import type { Locale } from '../types';

export const strings = {
  es: {
    mode: 'Modo',
    input: 'Texto o URL',
    placeholder: 'https://ejemplo.com/buscar?q=café con leche&orden=desc',
    variant: 'Variante',
    component: 'Componente (encodeURIComponent)',
    uri: 'URL completa (encodeURI)',
    plusAsSpace: 'Leer + como espacio',
    result: 'Resultado',
    encoded: 'Codificado',
    decoded: 'Decodificado',
    malformed: 'Secuencia % mal formada',
    malformedHint:
      'Cada % debe ir seguido de dos cifras hexadecimales (%20, %C3%A9). Si el % es literal, codifícalo como %25 o fuerza «Codificar».',
    empty: 'Escribe texto o pega una URL y el resultado aparecerá aquí.',
    parsed: 'Partes de la URL',
    invalidUrl: 'No es una URL válida',
    invalidUrlHint: 'Pega una URL completa, por ejemplo https://ejemplo.com/ruta?a=1.',
    parseEmpty: 'Pega una URL para ver sus partes.',
    assumed: 'No tenía esquema: se ha supuesto https://',
    protocol: 'Protocolo',
    host: 'Host',
    port: 'Puerto',
    defaultPort: '{port} (por defecto)',
    path: 'Ruta',
    hash: 'Fragmento',
    user: 'Usuario',
    password: 'Contraseña',
    params: 'Parámetros ({n})',
    noParams: 'Sin parámetros de consulta.',
    key: 'Clave',
    value: 'Valor',
    none: '—',
  },
  en: {
    mode: 'Mode',
    input: 'Text or URL',
    placeholder: 'https://example.com/search?q=café au lait&sort=desc',
    variant: 'Variant',
    component: 'Component (encodeURIComponent)',
    uri: 'Whole URL (encodeURI)',
    plusAsSpace: 'Read + as a space',
    result: 'Result',
    encoded: 'Encoded',
    decoded: 'Decoded',
    malformed: 'Malformed % sequence',
    malformedHint:
      'Every % must be followed by two hex digits (%20, %C3%A9). If the % is literal, write it as %25 or force “Encode”.',
    empty: 'Type text or paste a URL and the result will appear here.',
    parsed: 'URL parts',
    invalidUrl: 'Not a valid URL',
    invalidUrlHint: 'Paste a full URL, for example https://example.com/path?a=1.',
    parseEmpty: 'Paste a URL to see its parts.',
    assumed: 'It had no scheme: https:// was assumed',
    protocol: 'Protocol',
    host: 'Host',
    port: 'Port',
    defaultPort: '{port} (default)',
    path: 'Path',
    hash: 'Fragment',
    user: 'User',
    password: 'Password',
    params: 'Parameters ({n})',
    noParams: 'No query parameters.',
    key: 'Key',
    value: 'Value',
    none: '—',
  },
} satisfies Record<Locale, Record<string, string>>;
