import type { Locale } from '../types';

export const strings = {
  es: {
    input: 'Datos de entrada',
    placeholder: 'Pega JSON, YAML o CSV. Por ejemplo:\nnombre;edad\nAna;34',
    from: 'Formato de entrada',
    auto: 'Automático',
    to: 'Convertir a',
    sep: 'Separador',
    comma: 'Coma (,)',
    semicolon: 'Punto y coma (;)',
    tab: 'Tabulador',
    header: 'La primera fila es la cabecera',
    detectTypes: 'Detectar números y booleanos',
    result: 'Resultado',
    detected: 'Detectado: {format}',
    detectedCsv: 'Detectado: CSV (separador {sep})',
    read: 'Leído como {format}',
    errorAt: 'Error en la línea {line}, columna {column}: {message}',
    errorLine: 'Error en la línea {line}: {message}',
    unclosedQuote: 'Hay una comilla sin cerrar que empieza en la línea {line}',
    notTable: 'Para CSV hace falta una lista de objetos, por ejemplo [{"a": 1}]',
    columns: 'La fila {row} tiene {columns} columnas y la cabecera, {expected}',
    documents: 'Hay {n} documentos YAML separados por ---: se leen como una lista.',
    csvTypes:
      'CSV no guarda tipos: al volver a leerlo, todo será texto salvo que actives «Detectar números y booleanos».',
    dotted:
      'Hay claves con puntos: la cabecera las conserva, pero al volver a leer el CSV no se reconstruye el anidamiento.',
    empty: 'Pega datos en JSON, YAML o CSV y elige a qué formato convertirlos.',
    copyResult: 'Copiar resultado',
    file: 'datos',
    tabName: 'tabulador',
  },
  en: {
    input: 'Input data',
    placeholder: 'Paste JSON, YAML or CSV. For example:\nname;age\nAna;34',
    from: 'Input format',
    auto: 'Automatic',
    to: 'Convert to',
    sep: 'Separator',
    comma: 'Comma (,)',
    semicolon: 'Semicolon (;)',
    tab: 'Tab',
    header: 'First row is the header',
    detectTypes: 'Detect numbers and booleans',
    result: 'Result',
    detected: 'Detected: {format}',
    detectedCsv: 'Detected: CSV (separator {sep})',
    read: 'Read as {format}',
    errorAt: 'Error at line {line}, column {column}: {message}',
    errorLine: 'Error at line {line}: {message}',
    unclosedQuote: 'There is an unclosed quote starting at line {line}',
    notTable: 'CSV needs a list of objects, for example [{"a": 1}]',
    columns: 'Row {row} has {columns} columns and the header has {expected}',
    documents: 'There are {n} YAML documents separated by ---: they are read as a list.',
    csvTypes:
      'CSV does not store types: reading it back, everything will be text unless you turn on “Detect numbers and booleans”.',
    dotted:
      'Some keys contain dots: the header keeps them, but reading the CSV back does not rebuild the nesting.',
    empty: 'Paste JSON, YAML or CSV data and pick the format to convert it to.',
    copyResult: 'Copy result',
    file: 'data',
    tabName: 'tab',
  },
} satisfies Record<Locale, Record<string, string>>;
