import type { Locale } from '../types';

export const strings = {
  es: {
    tabs: 'Modo',
    notation: 'Dados',
    notationHelp: 'Como 3d6, 2d20+1 o d100.',
    quick: 'Dados rápidos',
    roll: 'Lanzar',
    coins: 'Monedas',
    flip: 'Lanzar',
    result: 'Tirada',
    idle: 'Pulsa Lanzar.',
    total: 'Total',
    sum: 'Suma',
    modifier: 'Modificador',
    range: 'Mínimo {min} · máximo {max}',
    format: 'Escribe los dados como 3d6, 2d20+1 o d100.',
    count: 'Entre 1 y 100 dados: has puesto {v}.',
    sides: 'Las caras van de 2 a 1000: has puesto {v}.',
    modifierRange: 'El modificador va de −1000 a 1000: has puesto {v}.',
    heads: 'Cara',
    tails: 'Cruz',
    coinCount: '{h} caras · {t} cruces',
    history: 'Últimas tiradas',
  },
  en: {
    tabs: 'Mode',
    notation: 'Dice',
    notationHelp: 'Like 3d6, 2d20+1 or d100.',
    quick: 'Quick dice',
    roll: 'Roll',
    coins: 'Coins',
    flip: 'Flip',
    result: 'Roll',
    idle: 'Press Roll.',
    total: 'Total',
    sum: 'Sum',
    modifier: 'Modifier',
    range: 'Minimum {min} · maximum {max}',
    format: 'Write the dice as 3d6, 2d20+1 or d100.',
    count: 'From 1 to 100 dice: you typed {v}.',
    sides: 'Faces go from 2 to 1000: you typed {v}.',
    modifierRange: 'The modifier goes from −1000 to 1000: you typed {v}.',
    heads: 'Heads',
    tails: 'Tails',
    coinCount: '{h} heads · {t} tails',
    history: 'Latest rolls',
  },
} satisfies Record<Locale, Record<string, string>>;
