import type { Locale } from '../types';

export const strings = {
  es: {
    mode: 'Modo',
    kind: 'Tipo',
    count: 'Cantidad',
    uppercase: 'Mayúsculas',
    dashes: 'Con guiones',
    size: 'Longitud',
    alphabet: 'Alfabeto',
    urlsafe: 'URL seguro (A-Z a-z 0-9 _ -)',
    alnum: 'Alfanumérico',
    hex: 'Hexadecimal',
    numbers: 'Solo números',
    result: 'Identificadores generados',
    copyAll: 'Copiar todos',
    file: 'identificadores.txt',
    input: 'Identificador',
    placeholder: 'Pega un UUID o un ULID',
    waiting: 'Pega un identificador y se analiza al momento.',
    uuid: 'UUID versión {v}',
    nil: 'UUID nulo (todo ceros)',
    max: 'UUID máximo (todo F)',
    ulid: 'ULID',
    invalid: 'No es un UUID ni un ULID válido',
    invalidHint:
      'Un UUID tiene 32 cifras hexadecimales (con o sin guiones) y un ULID, 26 caracteres en base32.',
    created: 'Creado el {date}',
    noDate: 'Esta versión no guarda la fecha de creación.',
    version: 'Versión',
    kindLabel: 'Tipo',
  },
  en: {
    mode: 'Mode',
    kind: 'Type',
    count: 'Count',
    uppercase: 'Uppercase',
    dashes: 'With dashes',
    size: 'Length',
    alphabet: 'Alphabet',
    urlsafe: 'URL-safe (A-Z a-z 0-9 _ -)',
    alnum: 'Alphanumeric',
    hex: 'Hexadecimal',
    numbers: 'Numbers only',
    result: 'Generated identifiers',
    copyAll: 'Copy all',
    file: 'identifiers.txt',
    input: 'Identifier',
    placeholder: 'Paste a UUID or a ULID',
    waiting: 'Paste an identifier and it is analysed right away.',
    uuid: 'UUID version {v}',
    nil: 'Nil UUID (all zeros)',
    max: 'Max UUID (all F)',
    ulid: 'ULID',
    invalid: 'Not a valid UUID or ULID',
    invalidHint:
      'A UUID has 32 hex digits (with or without dashes) and a ULID has 26 base32 characters.',
    created: 'Created on {date}',
    noDate: 'This version does not store a creation date.',
    version: 'Version',
    kindLabel: 'Type',
  },
} satisfies Record<Locale, Record<string, string>>;
