import type { Locale } from '../types';
import type { Gs1Prefix } from './logic';

export const strings = {
  es: {
    input: 'EAN-13 o ISBN',
    placeholder: '9780306406157\n0306406152',
    help: 'Uno por línea, hasta 1000. Con 12 o 9 cifras se calcula el dígito que falta.',
    result: 'Resultado',
    empty: 'Escribe un EAN-13 (13 cifras) o un ISBN-10 (10 caracteres).',
    validEan: 'EAN-13 válido',
    validIsbn13: 'ISBN-13 válido',
    validIsbn10: 'ISBN-10 válido',
    count: '{ok} válidos · {bad} no válidos',
    truncated: 'Solo se comprueban las primeras {n} líneas.',
    format: 'Formato',
    isbn10: 'ISBN-10',
    isbn13: 'ISBN-13',
    prefix: 'Prefijo GS1',
    no979: 'Los ISBN que empiezan por 979 no tienen equivalente de 10 cifras.',
    errEanCheck: 'El dígito de control no cuadra: debería ser {e} ({c}).',
    errIsbnCheck: 'El dígito de control no cuadra: debería ser {e} ({c}).',
    errEanMissing: 'Falta el dígito de control: sería {e} ({c}).',
    errIsbnMissing: 'Falta el dígito de control: sería {e} ({c}).',
    errEan8: 'EAN-8 no está incluido.',
    errLength: 'Longitud no admitida ({n}): usa 13 o 12 cifras (EAN-13) o 10 o 9 (ISBN-10).',
    errX: 'La X solo puede ir al final de un ISBN-10.',
    errChars: 'Solo cifras, espacios, guiones y la X final de un ISBN-10.',
  },
  en: {
    input: 'EAN-13 or ISBN',
    placeholder: '9780306406157\n0306406152',
    help: 'One per line, up to 1000. With 12 or 9 digits the missing check digit is worked out.',
    result: 'Result',
    empty: 'Type an EAN-13 (13 digits) or an ISBN-10 (10 characters).',
    validEan: 'Valid EAN-13',
    validIsbn13: 'Valid ISBN-13',
    validIsbn10: 'Valid ISBN-10',
    count: '{ok} valid · {bad} not valid',
    truncated: 'Only the first {n} lines are checked.',
    format: 'Format',
    isbn10: 'ISBN-10',
    isbn13: 'ISBN-13',
    prefix: 'GS1 prefix',
    no979: 'ISBNs starting with 979 have no 10-digit equivalent.',
    errEanCheck: 'The check digit does not match: it should be {e} ({c}).',
    errIsbnCheck: 'The check digit does not match: it should be {e} ({c}).',
    errEanMissing: 'The check digit is missing: it would be {e} ({c}).',
    errIsbnMissing: 'The check digit is missing: it would be {e} ({c}).',
    errEan8: 'EAN-8 is not included.',
    errLength: 'Unsupported length ({n}): use 13 or 12 digits (EAN-13) or 10 or 9 (ISBN-10).',
    errX: 'X can only be the last character of an ISBN-10.',
    errChars: 'Digits, spaces, dashes and the final X of an ISBN-10 only.',
  },
} satisfies Record<Locale, Record<string, string>>;

export const prefixNames: Record<Locale, Record<Exclude<Gs1Prefix, null>, string>> = {
  es: {
    spain: '84 · España',
    isbn: '978/979 · Libros (ISBN)',
    ismn: '9790 · Partituras (ISMN)',
    issn: '977 · Publicaciones periódicas (ISSN)',
    store: '20–29 · Uso interno de tienda',
  },
  en: {
    spain: '84 · Spain',
    isbn: '978/979 · Books (ISBN)',
    ismn: '9790 · Sheet music (ISMN)',
    issn: '977 · Periodicals (ISSN)',
    store: '20–29 · In-store use',
  },
};
