import type { Locale } from '../types';

export const strings = {
  es: {
    input: 'User-Agent',
    placeholder: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0',
    useMine: 'Usar el de este navegador',
    result: 'Análisis',
    browser: 'Navegador',
    engine: 'Motor',
    os: 'Sistema',
    device: 'Dispositivo',
    cpu: 'CPU',
    desktop: 'Escritorio (probable)',
    console: 'Consola',
    mobile: 'Móvil',
    smarttv: 'Smart TV',
    tablet: 'Tableta',
    wearable: 'Dispositivo ponible',
    embedded: 'Dispositivo integrado',
    bot: 'Parece un bot o un rastreador',
    notRecognised: 'No se ha reconocido ningún navegador',
    recognised: 'Reconocido',
    empty: 'Pega un User-Agent o usa el de este navegador.',
    hints: 'Client Hints de este navegador',
    brands: 'Marcas',
    platform: 'Plataforma',
    isMobile: 'Móvil',
    yes: 'Sí',
    no: 'No',
    frozen:
      'Desde 2021, Chrome y otros navegadores congelan parte del User-Agent (la versión menor y la del sistema). Para datos precisos hacen falta las Client Hints.',
    copyReport: 'Copiar análisis',
  },
  en: {
    input: 'User-Agent',
    placeholder: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0',
    useMine: 'Use this browser’s',
    result: 'Analysis',
    browser: 'Browser',
    engine: 'Engine',
    os: 'OS',
    device: 'Device',
    cpu: 'CPU',
    desktop: 'Desktop (likely)',
    console: 'Console',
    mobile: 'Mobile',
    smarttv: 'Smart TV',
    tablet: 'Tablet',
    wearable: 'Wearable',
    embedded: 'Embedded device',
    bot: 'Looks like a bot or crawler',
    notRecognised: 'No browser was recognised',
    recognised: 'Recognised',
    empty: 'Paste a User-Agent or use this browser’s.',
    hints: 'This browser’s Client Hints',
    brands: 'Brands',
    platform: 'Platform',
    isMobile: 'Mobile',
    yes: 'Yes',
    no: 'No',
    frozen:
      'Since 2021 Chrome and other browsers freeze part of the User-Agent (the minor version and the OS version). Precise data needs Client Hints.',
    copyReport: 'Copy analysis',
  },
} satisfies Record<Locale, Record<string, string>>;
