import type { Locale } from '../types';

export const strings = {
  es: {
    direction: 'Dirección',
    auto: 'Automática',
    toJson: 'Query → JSON',
    toQuery: 'JSON → query',
    input: 'Query string, URL o JSON',
    placeholder: 'https://example.com/buscar?q=gato&tags[]=a&tags[]=b',
    brackets: 'Notación con corchetes',
    detectTypes: 'Detectar números y booleanos',
    plus: 'Espacios como +',
    result: 'Resultado',
    detectedJson: 'Detectado: query → JSON',
    detectedQuery: 'Detectado: JSON → query',
    empty: 'Pega una URL, una query string (a=1&b=2) o un JSON con un objeto.',
    pairs: 'Pares decodificados',
    key: 'Clave',
    value: 'Valor',
    noPairs: 'No hay parámetros.',
    undecodable: 'No se pudo decodificar {seq}: se deja tal cual',
    notObject: 'El JSON debe ser un objeto, por ejemplo {"q": "gato", "page": 2}',
    jsonError: 'JSON no válido en la línea {line}, columna {column}',
    jsonErrorNoLine: 'El JSON no es válido',
    notSaved: 'Hay claves que parecen credenciales: esta entrada no se guarda.',
    notSavedCredentials: 'La URL lleva credenciales: esta entrada no se guarda.',
    copyResult: 'Copiar resultado',
  },
  en: {
    direction: 'Direction',
    auto: 'Automatic',
    toJson: 'Query → JSON',
    toQuery: 'JSON → query',
    input: 'Query string, URL or JSON',
    placeholder: 'https://example.com/search?q=cat&tags[]=a&tags[]=b',
    brackets: 'Bracket notation',
    detectTypes: 'Detect numbers and booleans',
    plus: 'Spaces as +',
    result: 'Result',
    detectedJson: 'Detected: query → JSON',
    detectedQuery: 'Detected: JSON → query',
    empty: 'Paste a URL, a query string (a=1&b=2) or a JSON object.',
    pairs: 'Decoded pairs',
    key: 'Key',
    value: 'Value',
    noPairs: 'There are no parameters.',
    undecodable: 'Could not decode {seq}: left as it is',
    notObject: 'The JSON must be an object, for example {"q": "cat", "page": 2}',
    jsonError: 'Invalid JSON at line {line}, column {column}',
    jsonErrorNoLine: 'The JSON is not valid',
    notSaved: 'Some keys look like credentials: this input is not saved.',
    notSavedCredentials: 'The URL carries credentials: this input is not saved.',
    copyResult: 'Copy result',
  },
} satisfies Record<Locale, Record<string, string>>;
