import type { Locale } from '../types';

export const strings = {
  es: {
    range: 'Rango',
    rangePlaceholder: '^1.2.3',
    versions: 'Versiones (una por línea)',
    versionsPlaceholder: '1.2.3\n1.9.0\n2.0.0',
    includePrerelease: 'Incluir prereleases',
    result: 'Resultado',
    badRange: 'El rango no es válido. Ejemplos: ^1.2.3, ~1.2, >=1.0.0 <2.0.0, 1.x || 2.x',
    badVersion: 'No es una versión semver: se escribe MAYOR.MENOR.PARCHE, por ejemplo 1.4.0',
    empty: 'Escribe un rango como ^1.2.3 y las versiones que quieras comprobar.',
    noVersions: 'Escribe una o más versiones, una por línea, para comprobarlas con el rango.',
    normalized: 'Rango normalizado',
    reading: 'En palabras',
    min: 'Versión mínima del rango',
    max: 'La más alta que cumple',
    none: 'Ninguna',
    matches: '{n} de {total} cumplen',
    yes: 'Cumple',
    no: 'No cumple',
    copyRange: 'Copiar rango',
    cheatsheet: 'Chuleta de rangos',
    cheatCaret: 'Mismo número mayor: >=1.2.3 <2.0.0 (con 0.x, mismo menor)',
    cheatTilde: 'Solo parches: >=1.2.3 <1.3.0',
    cheatX: 'Comodín: 1.x = >=1.0.0 <2.0.0',
    cheatHyphen: 'Intervalo cerrado: >=1.2.3 <=2.3.4',
    cheatOr: 'Cualquiera de los dos rangos',
  },
  en: {
    range: 'Range',
    rangePlaceholder: '^1.2.3',
    versions: 'Versions (one per line)',
    versionsPlaceholder: '1.2.3\n1.9.0\n2.0.0',
    includePrerelease: 'Include prereleases',
    result: 'Result',
    badRange: 'The range is not valid. Examples: ^1.2.3, ~1.2, >=1.0.0 <2.0.0, 1.x || 2.x',
    badVersion: 'Not a semver version: write MAJOR.MINOR.PATCH, for example 1.4.0',
    empty: 'Type a range such as ^1.2.3 and the versions you want to check.',
    noVersions: 'Write one or more versions, one per line, to check them against the range.',
    normalized: 'Normalised range',
    reading: 'In words',
    min: 'Lowest version in range',
    max: 'Highest that satisfies',
    none: 'None',
    matches: '{n} of {total} satisfy',
    yes: 'Satisfies',
    no: 'Does not satisfy',
    copyRange: 'Copy range',
    cheatsheet: 'Range cheat sheet',
    cheatCaret: 'Same major: >=1.2.3 <2.0.0 (with 0.x, same minor)',
    cheatTilde: 'Patches only: >=1.2.3 <1.3.0',
    cheatX: 'Wildcard: 1.x = >=1.0.0 <2.0.0',
    cheatHyphen: 'Closed interval: >=1.2.3 <=2.3.4',
    cheatOr: 'Either range',
  },
} satisfies Record<Locale, Record<string, string>>;
