import type { Locale } from '../types';

export const strings = {
  es: {
    mode: 'Modo',
    input: 'IBAN o CCC',
    placeholder: 'ES91 2100 0418 4502 0005 1332',
    help: 'Uno por línea, hasta 1000. Un número de cuenta no se guarda en ningún sitio.',
    result: 'Resultado',
    empty: 'Escribe un IBAN de cualquier país o un CCC español de 20 cifras.',
    valid: 'IBAN válido',
    count: '{ok} válidos · {bad} no válidos',
    truncated: 'Solo se comprueban las primeras {n} líneas.',
    country: 'País',
    bank: 'Entidad',
    branch: 'Oficina',
    dc: 'DC',
    account: 'Cuenta',
    bban: 'BBAN',
    fromCcc: 'Era un CCC válido: este es su IBAN.',
    errCountry: '{c} no usa IBAN o no está en el registro de IBAN.',
    errLength: 'Un IBAN de {country} tiene {n} caracteres y este tiene {m}.',
    errChars: 'Solo se admiten letras de la A a la Z y cifras.',
    errCheckRange: 'Los dígitos de control (posiciones 3 y 4) van de 02 a 98.',
    errChecksum: 'Los dígitos de control no cuadran: hay alguna errata en el número.',
    errCcc: 'El IBAN es coherente, pero los dígitos de control de la cuenta no: deberían ser {e}.',
    errCccOnly: 'Los dígitos de control de la cuenta no cuadran: deberían ser {e}.',
    group: 'Agrupar de 4 en 4',
    generated: 'IBAN generados',
    copyIban: 'IBAN',
    copyCcc: 'CCC',
    copyAll: 'Copiar todos',
  },
  en: {
    mode: 'Mode',
    input: 'IBAN or CCC',
    placeholder: 'ES91 2100 0418 4502 0005 1332',
    help: 'One per line, up to 1000. Account numbers are not stored anywhere.',
    result: 'Result',
    empty: 'Type an IBAN from any country or a 20-digit Spanish CCC.',
    valid: 'Valid IBAN',
    count: '{ok} valid · {bad} not valid',
    truncated: 'Only the first {n} lines are checked.',
    country: 'Country',
    bank: 'Bank',
    branch: 'Branch',
    dc: 'Check digits',
    account: 'Account',
    bban: 'BBAN',
    fromCcc: 'It was a valid CCC: this is its IBAN.',
    errCountry: '{c} does not use IBAN or is not in the IBAN registry.',
    errLength: 'An IBAN from {country} has {n} characters and this one has {m}.',
    errChars: 'Only letters A to Z and digits are allowed.',
    errCheckRange: 'The check digits (positions 3 and 4) go from 02 to 98.',
    errChecksum: 'The check digits do not match: there is a typo somewhere in the number.',
    errCcc: 'The IBAN is consistent, but the account check digits are not: they should be {e}.',
    errCccOnly: 'The account check digits do not match: they should be {e}.',
    group: 'Group in fours',
    generated: 'Generated IBANs',
    copyIban: 'IBAN',
    copyCcc: 'CCC',
    copyAll: 'Copy all',
  },
} satisfies Record<Locale, Record<string, string>>;
