import type { Locale } from '../types';

export const strings = {
  es: {
    input: 'Códigos postales',
    placeholder: '28013\n8001',
    help: 'Uno por línea, hasta 1000.',
    result: 'Resultado',
    empty: 'Escribe un código postal de 5 cifras (o de 4, si se perdió el 0 inicial).',
    valid: 'Código válido',
    count: '{ok} válidos · {bad} no válidos',
    truncated: 'Solo se comprueban las primeras {n} líneas.',
    province: 'Provincia',
    community: 'Comunidad',
    capital: 'Capital',
    padded: 'Añadido el 0 inicial: {code}.',
    errPrefix: 'Ningún código postal empieza por {p}: los prefijos van de 01 a 52.',
    errLength: 'Un código postal tiene 5 cifras (o 4 si se perdió el 0 inicial).',
    errChars: 'Solo cifras.',
    reverse: 'Buscar por provincia',
    range: 'Rango',
    rangeText: 'Los códigos postales de {name} van de {from} a {to}.',
  },
  en: {
    input: 'Postal codes',
    placeholder: '28013\n8001',
    help: 'One per line, up to 1000.',
    result: 'Result',
    empty: 'Type a 5-digit postal code (or 4 digits, if the leading 0 was lost).',
    valid: 'Valid code',
    count: '{ok} valid · {bad} not valid',
    truncated: 'Only the first {n} lines are checked.',
    province: 'Province',
    community: 'Region',
    capital: 'Capital',
    padded: 'Leading 0 added: {code}.',
    errPrefix: 'No postal code starts with {p}: prefixes go from 01 to 52.',
    errLength: 'A postal code has 5 digits (or 4 if the leading 0 was lost).',
    errChars: 'Digits only.',
    reverse: 'Look up by province',
    range: 'Range',
    rangeText: 'Postal codes in {name} go from {from} to {to}.',
  },
} satisfies Record<Locale, Record<string, string>>;
