import type { Locale } from '../types';

export const strings = {
  es: {
    input: 'IP y prefijo o máscara',
    placeholder: '192.168.1.10/24',
    help: 'Admite 10.0.0.1/8, 10.0.0.1 255.0.0.0 o una IP sola.',
    assumed32: 'Sin prefijo, se toma como /32 (un solo equipo).',
    result: 'Subred',
    empty: 'Escribe una dirección IPv4 con su prefijo, por ejemplo 192.168.1.10/24.',
    ip: 'IP',
    network: 'Red',
    mask: 'Máscara',
    wildcard: 'Comodín',
    broadcast: 'Broadcast',
    first: 'Primer host',
    last: 'Último host',
    usable: 'Hosts útiles',
    total: 'Direcciones en total',
    binary: 'Máscara en binario',
    type: 'Tipo',
    class: 'Clase histórica',
    none: '—',
    private: 'Privada (RFC 1918)',
    cgnat: 'CGNAT (RFC 6598)',
    loopback: 'Loopback',
    'link-local': 'Enlace local',
    'this-network': '«Esta red» (0.0.0.0/8)',
    documentation: 'Documentación (RFC 5737)',
    multicast: 'Multicast',
    reserved: 'Reservada',
    public: 'Pública',
    format: 'Escribe cuatro números separados por puntos, como 192.168.1.10/24',
    leadingZero:
      'Los ceros a la izquierda son ambiguos (hay sistemas que los leen en octal): escribe {fixed}',
    octetRange: 'El número {octet} no vale en una IP: cada parte va de 0 a 255',
    prefix: 'El prefijo /{prefix} no existe: va de 0 a 32',
    badMask: 'La máscara no es válida: los unos deben ir seguidos',
    ipv6: 'IPv6 todavía no está incluido',
    copyNetwork: 'Copiar red',
  },
  en: {
    input: 'IP and prefix or mask',
    placeholder: '192.168.1.10/24',
    help: 'Accepts 10.0.0.1/8, 10.0.0.1 255.0.0.0 or a bare IP.',
    assumed32: 'Without a prefix it is taken as /32 (a single host).',
    result: 'Subnet',
    empty: 'Type an IPv4 address with its prefix, for example 192.168.1.10/24.',
    ip: 'IP',
    network: 'Network',
    mask: 'Mask',
    wildcard: 'Wildcard',
    broadcast: 'Broadcast',
    first: 'First host',
    last: 'Last host',
    usable: 'Usable hosts',
    total: 'Total addresses',
    binary: 'Mask in binary',
    type: 'Type',
    class: 'Historic class',
    none: '—',
    private: 'Private (RFC 1918)',
    cgnat: 'CGNAT (RFC 6598)',
    loopback: 'Loopback',
    'link-local': 'Link-local',
    'this-network': '“This network” (0.0.0.0/8)',
    documentation: 'Documentation (RFC 5737)',
    multicast: 'Multicast',
    reserved: 'Reserved',
    public: 'Public',
    format: 'Type four numbers separated by dots, such as 192.168.1.10/24',
    leadingZero: 'Leading zeros are ambiguous (some systems read them as octal): write {fixed}',
    octetRange: '{octet} is not valid in an IP: each part goes from 0 to 255',
    prefix: 'The prefix /{prefix} does not exist: it goes from 0 to 32',
    badMask: 'The mask is not valid: its ones must be contiguous',
    ipv6: 'IPv6 is not included yet',
    copyNetwork: 'Copy network',
  },
} satisfies Record<Locale, Record<string, string>>;
