import type { Locale } from '../types';
import type { CifType } from './logic';

export const strings = {
  es: {
    mode: 'Modo',
    input: 'CIF',
    placeholder: 'B65410011\nQ2826000H',
    help: 'Uno por línea, hasta 1000. Los DNI, NIE y NIF de personas (K, L y M) nunca se guardan.',
    result: 'Resultado',
    empty: 'Escribe un CIF (B65410011) y se comprueba al momento.',
    valid: 'CIF válido',
    validPerson: 'NIF especial de persona física',
    validOne: '{n} válido',
    validOther: '{n} válidos',
    invalidOne: '{n} no válido',
    invalidOther: '{n} no válidos',
    truncated: 'Solo se comprueban las primeras {n} líneas.',
    entity: 'Entidad',
    expected: 'Control esperado',
    accepted: 'Forma aceptada',
    digitAndLetter: '{d} (cifra) · {l} (letra)',
    digit: 'Cifra',
    letter: 'Letra',
    either: 'Cifra o letra',
    or: ' o ',
    control: 'El control no cuadra: para {body} debería ser {e}.',
    needsLetter: 'Una entidad de tipo {t} lleva letra de control: sería {e}.',
    needsDigit: 'Una entidad de tipo {t} lleva cifra de control: sería {e}.',
    missingControl: 'Falta el carácter de control: para {body} sería {e}.',
    type: 'La letra {t} no corresponde a ningún tipo de entidad.',
    digitFirst:
      'Un CIF empieza por la letra del tipo de entidad. Si es un DNI o un NIE, compruébalo en el validador de DNI.',
    format:
      'Formato no reconocido: un CIF es una letra, 7 cifras y un carácter de control (B65410011).',
    typeLabel: 'Tipo de entidad',
    any: 'Cualquiera (A o B)',
    generated: 'CIF generados',
    copyAll: 'Copiar todos',
  },
  en: {
    mode: 'Mode',
    input: 'CIF',
    placeholder: 'B65410011\nQ2826000H',
    help: 'One per line, up to 1000. A DNI, an NIE and tax IDs of people (K, L and M) are never stored.',
    result: 'Result',
    empty: 'Type a CIF (B65410011) and it is checked right away.',
    valid: 'Valid CIF',
    validPerson: 'Special tax ID of a person',
    validOne: '{n} valid',
    validOther: '{n} valid',
    invalidOne: '{n} not valid',
    invalidOther: '{n} not valid',
    truncated: 'Only the first {n} lines are checked.',
    entity: 'Entity',
    expected: 'Expected check',
    accepted: 'Accepted form',
    digitAndLetter: '{d} (digit) · {l} (letter)',
    digit: 'Digit',
    letter: 'Letter',
    either: 'Digit or letter',
    or: ' or ',
    control: 'The check does not match: for {body} it should be {e}.',
    needsLetter: 'An entity of type {t} takes a check letter: it would be {e}.',
    needsDigit: 'An entity of type {t} takes a check digit: it would be {e}.',
    missingControl: 'The check character is missing: for {body} it would be {e}.',
    type: 'The letter {t} is not an entity type.',
    digitFirst:
      'A CIF starts with the letter of its entity type. If this is a DNI or an NIE, check it in the DNI validator.',
    format: 'Unrecognised format: a CIF is a letter, 7 digits and a check character (B65410011).',
    typeLabel: 'Entity type',
    any: 'Any (A or B)',
    generated: 'Generated CIF',
    copyAll: 'Copy all',
  },
} satisfies Record<Locale, Record<string, string>>;

export const entityNames: Record<Locale, Record<CifType | 'K' | 'L' | 'M', string>> = {
  es: {
    A: 'Sociedad anónima',
    B: 'Sociedad de responsabilidad limitada',
    C: 'Sociedad colectiva',
    D: 'Sociedad comanditaria',
    E: 'Comunidad de bienes',
    F: 'Sociedad cooperativa',
    G: 'Asociación o fundación',
    H: 'Comunidad de propietarios',
    J: 'Sociedad civil',
    N: 'Entidad extranjera',
    P: 'Corporación local',
    Q: 'Organismo público',
    R: 'Congregación o institución religiosa',
    S: 'Órgano de la Administración del Estado o autonómica',
    U: 'Unión temporal de empresas',
    V: 'Otros tipos',
    W: 'Establecimiento permanente de entidad no residente',
    K: 'Menor de 14 años sin DNI',
    L: 'Español residente en el extranjero sin DNI',
    M: 'Extranjero sin NIE',
  },
  en: {
    A: 'Public limited company (S.A.)',
    B: 'Limited liability company (S.L.)',
    C: 'General partnership',
    D: 'Limited partnership',
    E: 'Joint ownership',
    F: 'Cooperative',
    G: 'Association or foundation',
    H: 'Owners’ association',
    J: 'Civil partnership',
    N: 'Foreign entity',
    P: 'Local authority',
    Q: 'Public body',
    R: 'Religious congregation or institution',
    S: 'State or regional government body',
    U: 'Temporary business association (UTE)',
    V: 'Other types',
    W: 'Permanent establishment of a non-resident entity',
    K: 'Under-14 without a DNI',
    L: 'Spaniard living abroad without a DNI',
    M: 'Foreigner without an NIE',
  },
};
