import type { Locale } from '../types';

export const strings = {
  es: {
    people: 'Participantes',
    peopleHelp: 'Una persona por línea.',
    mode: 'Repartir por',
    count: 'Número de equipos',
    size: 'Personas por equipo',
    n: 'N',
    prefix: 'Nombre de los equipos',
    prefixDefault: 'Equipo',
    make: 'Hacer equipos',
    result: 'Equipos',
    peopleCountOne: '{n} persona',
    peopleCountOther: '{n} personas',
    teamsCountOne: '{n} equipo',
    teamsCountOther: '{n} equipos',
    summary: '{people} en {teams}',
    few: 'Añade al menos dos personas.',
    nInvalid: '{label} debe ser un número entero mayor que 0.',
    tooMany: 'Hay {people} y {teams}: baja el número de equipos.',
    balanced:
      'Con {people} y {n} por equipo salen {teams} de {sizes}: se reparten para que nadie se quede solo.',
    copyAll: 'Copiar los equipos',
  },
  en: {
    people: 'Participants',
    peopleHelp: 'One person per line.',
    mode: 'Split by',
    count: 'Number of teams',
    size: 'People per team',
    n: 'N',
    prefix: 'Team name',
    prefixDefault: 'Team',
    make: 'Make teams',
    result: 'Teams',
    peopleCountOne: '{n} person',
    peopleCountOther: '{n} people',
    teamsCountOne: '{n} team',
    teamsCountOther: '{n} teams',
    summary: '{people} in {teams}',
    few: 'Add at least two people.',
    nInvalid: '{label} must be a whole number greater than 0.',
    tooMany: 'There are {people} and {teams}: lower the number of teams.',
    balanced:
      'With {people} and {n} per team you get {teams} of {sizes}: they are balanced so nobody is left alone.',
    copyAll: 'Copy the teams',
  },
} satisfies Record<Locale, Record<string, string>>;
