import type { Locale } from '../types';
import type { SentenceWords } from './logic';

export const strings = {
  es: {
    octal: 'Octal',
    symbolic: 'Simbólico',
    symbolicHelp: 'Como en ls -l: rwxr-xr-x o -rwxr-xr-x.',
    grid: 'Permisos',
    who: 'Quién',
    owner: 'Propietario',
    group: 'Grupo',
    others: 'Otros',
    r: 'Lectura',
    w: 'Escritura',
    x: 'Ejecución',
    special: 'Bits especiales',
    setuid: 'setuid',
    setgid: 'setgid',
    sticky: 'sticky',
    presets: 'Valores habituales',
    result: 'Resultado',
    command: 'Orden',
    commandSymbolic: 'Orden simbólica',
    ls: 'Como en ls -l',
    file: 'archivo',
    worldWritable: 'Cualquier usuario podrá modificar el archivo.',
    digit: '{d} no es una cifra octal: cada cifra va de 0 a 7.',
    length: 'Escribe 3 o 4 cifras octales, como 755 o 4755.',
    symLength: 'Escribe 9 caracteres (rwxr-xr-x) o 10 con el tipo delante (-rwxr-xr-x).',
    symChar: 'El carácter {p} («{c}») no vale ahí: se espera {e}.',
    setuidNote: 'setuid: al ejecutarlo, corre con los permisos del propietario.',
    setgidNote:
      'setgid: corre con los permisos del grupo; en un directorio, lo nuevo hereda su grupo.',
    stickyNote: 'sticky: en un directorio, solo el dueño de cada archivo puede borrarlo.',
  },
  en: {
    octal: 'Octal',
    symbolic: 'Symbolic',
    symbolicHelp: 'Like ls -l: rwxr-xr-x or -rwxr-xr-x.',
    grid: 'Permissions',
    who: 'Who',
    owner: 'Owner',
    group: 'Group',
    others: 'Others',
    r: 'Read',
    w: 'Write',
    x: 'Execute',
    special: 'Special bits',
    setuid: 'setuid',
    setgid: 'setgid',
    sticky: 'sticky',
    presets: 'Common values',
    result: 'Result',
    command: 'Command',
    commandSymbolic: 'Symbolic command',
    ls: 'Like ls -l',
    file: 'file',
    worldWritable: 'Any user will be able to modify the file.',
    digit: '{d} is not an octal digit: each digit goes from 0 to 7.',
    length: 'Type 3 or 4 octal digits, like 755 or 4755.',
    symLength: 'Type 9 characters (rwxr-xr-x) or 10 with the type first (-rwxr-xr-x).',
    symChar: 'Character {p} ("{c}") is not valid there: expected {e}.',
    setuidNote: 'setuid: when run, it gets the owner’s permissions.',
    setgidNote:
      'setgid: it runs with the group’s permissions; in a directory, new files inherit its group.',
    stickyNote: 'sticky: in a directory, only the owner of each file can delete it.',
  },
} satisfies Record<Locale, Record<string, string>>;

export const sentenceWords: Record<Locale, SentenceWords> = {
  es: {
    owner: 'el propietario',
    group: 'el grupo',
    others: 'los demás',
    r: 'leer',
    w: 'escribir',
    x: 'ejecutar',
    can: 'puede',
    canPlural: 'pueden',
    nothing: 'no tiene ningún permiso',
    nothingPlural: 'no tienen ningún permiso',
    none: 'nada',
  },
  en: {
    owner: 'the owner',
    group: 'the group',
    others: 'others',
    r: 'read',
    w: 'write',
    x: 'execute',
    can: 'can',
    canPlural: 'can',
    nothing: 'has no permissions',
    nothingPlural: 'have no permissions',
    none: 'nothing',
  },
};
