import type { Locale } from '../types';

export const strings = {
  es: {
    tabs: 'Cálculo',
    x: 'Porcentaje (X)',
    y: 'Número (Y)',
    whatX: 'Cantidad (X)',
    whatY: 'Total (Y)',
    a: 'Valor inicial (A)',
    b: 'Valor final (B)',
    result: 'Resultado',
    of: '{x} % de {y} es {v}',
    plus: '{y} + {x} % = {v}',
    minus: '{y} − {x} % = {v}',
    what: '{x} es el {v} % de {y}',
    increase: 'De {a} a {b} es un aumento del {v} %',
    decrease: 'De {a} a {b} es una disminución del {v} %',
    none: 'De {a} a {b} no hay variación (0 %)',
    invalid: 'Escribe un número, por ejemplo 1234,5.',
    zeroY: 'No se puede dividir entre 0: Y debe ser distinto de 0.',
    zeroA: 'No hay variación porcentual desde 0: el valor inicial tiene que ser distinto de 0.',
  },
  en: {
    tabs: 'Calculation',
    x: 'Percentage (X)',
    y: 'Number (Y)',
    whatX: 'Amount (X)',
    whatY: 'Total (Y)',
    a: 'Start value (A)',
    b: 'End value (B)',
    result: 'Result',
    of: '{x}% of {y} is {v}',
    plus: '{y} + {x}% = {v}',
    minus: '{y} − {x}% = {v}',
    what: '{x} is {v}% of {y}',
    increase: 'From {a} to {b} is a {v}% increase',
    decrease: 'From {a} to {b} is a {v}% decrease',
    none: 'From {a} to {b} there is no change (0%)',
    invalid: 'Type a number, for example 1234.5.',
    zeroY: 'Cannot divide by 0: Y must not be 0.',
    zeroA: 'There is no percentage change from 0: the starting value must be non-zero.',
  },
} satisfies Record<Locale, Record<string, string>>;
