import type { Locale } from '../types';

export const strings = {
  es: {
    input: 'Token',
    placeholder: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIn0.firma',
    warning:
      'La firma no se verifica. Cualquiera puede crear un JWT con este contenido: no confíes en él sin validarlo en tu servidor.',
    notStored: 'El token no se guarda en ningún sitio.',
    status: 'Estado',
    valid: 'Vigente',
    expired: 'Caducado',
    notYet: 'Aún no es válido',
    none: 'Sin fecha de caducidad',
    invalid: 'No es un JWT válido',
    errorParts:
      'Un JWT tiene tres partes separadas por puntos (cabecera.payload.firma). Este tiene {n}.',
    errorHeader: 'La cabecera (primera parte) no es Base64url con un objeto JSON.',
    errorPayload: 'El payload (segunda parte) no es Base64url con un objeto JSON.',
    empty: 'Pega un JWT (también vale con «Bearer » delante) y se decodifica al momento.',
    header: 'Cabecera',
    payload: 'Payload',
    dates: 'Fechas',
    exp: 'Caduca (exp)',
    nbf: 'Válido desde (nbf)',
    iat: 'Emitido (iat)',
    noDates: 'Este token no tiene fechas (exp, nbf, iat).',
    signature: 'Firma',
    algorithm: 'Algoritmo',
    copyHeader: 'Copiar cabecera',
    copyPayload: 'Copiar payload',
  },
  en: {
    input: 'Token',
    placeholder: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIn0.signature',
    warning:
      'The signature is not verified. Anyone can create a JWT with this content: do not trust it without validating it on your server.',
    notStored: 'The token is not stored anywhere.',
    status: 'Status',
    valid: 'Valid',
    expired: 'Expired',
    notYet: 'Not valid yet',
    none: 'No expiry date',
    invalid: 'Not a valid JWT',
    errorParts:
      'A JWT has three parts separated by dots (header.payload.signature). This one has {n}.',
    errorHeader: 'The header (first part) is not Base64url with a JSON object.',
    errorPayload: 'The payload (second part) is not Base64url with a JSON object.',
    empty: 'Paste a JWT (a leading “Bearer ” is fine) and it is decoded right away.',
    header: 'Header',
    payload: 'Payload',
    dates: 'Dates',
    exp: 'Expires (exp)',
    nbf: 'Valid from (nbf)',
    iat: 'Issued (iat)',
    noDates: 'This token has no dates (exp, nbf, iat).',
    signature: 'Signature',
    algorithm: 'Algorithm',
    copyHeader: 'Copy header',
    copyPayload: 'Copy payload',
  },
} satisfies Record<Locale, Record<string, string>>;
