import type { Locale } from '../types';

export const strings = {
  es: {
    now: 'Ahora',
    seconds: 'Segundos',
    millis: 'Milisegundos',
    copySeconds: 'Copiar segundos',
    copyMillis: 'Copiar milisegundos',
    zone: 'Zona horaria',
    toDate: 'Timestamp → fecha',
    timestamp: 'Timestamp',
    timestampPlaceholder: '1700000000 o 1700000000000',
    unit: 'Unidad',
    auto: 'Detectar',
    detected: 'Detectado: {unit}',
    unitS: 'segundos',
    unitMs: 'milisegundos',
    invalidTs: 'No es un timestamp válido',
    invalidTsHint:
      'Escribe solo cifras (con «-» para fechas anteriores a 1970), en segundos o milisegundos.',
    emptyTs: 'Escribe un timestamp y verás la fecha en todos los formatos.',
    iso: 'ISO 8601 (UTC)',
    utc: 'UTC',
    local: 'Hora en la zona',
    offsetOutOfRange: 'desfase fuera de rango',
    relative: 'Relativo',
    toTimestamp: 'Fecha → timestamp',
    date: 'Fecha',
    datePlaceholder: '2026-09-26 14:30 o 2026-09-26T12:30:00Z',
    dateHelp: 'Sin «Z» ni desfase (+02:00), la fecha se lee en la zona horaria elegida.',
    invalidDate: 'No se reconoce la fecha. Prueba con el formato AAAA-MM-DD HH:MM.',
    useNow: 'Usar ahora',
  },
  en: {
    now: 'Now',
    seconds: 'Seconds',
    millis: 'Milliseconds',
    copySeconds: 'Copy seconds',
    copyMillis: 'Copy milliseconds',
    zone: 'Time zone',
    toDate: 'Timestamp → date',
    timestamp: 'Timestamp',
    timestampPlaceholder: '1700000000 or 1700000000000',
    unit: 'Unit',
    auto: 'Detect',
    detected: 'Detected: {unit}',
    unitS: 'seconds',
    unitMs: 'milliseconds',
    invalidTs: 'Not a valid timestamp',
    invalidTsHint: 'Type digits only (with “-” for dates before 1970), in seconds or milliseconds.',
    emptyTs: 'Type a timestamp to see the date in every format.',
    iso: 'ISO 8601 (UTC)',
    utc: 'UTC',
    local: 'Time in zone',
    offsetOutOfRange: 'offset out of range',
    relative: 'Relative',
    toTimestamp: 'Date → timestamp',
    date: 'Date',
    datePlaceholder: '2026-09-26 14:30 or 2026-09-26T12:30:00Z',
    dateHelp: 'Without “Z” or an offset (+02:00), the date is read in the chosen time zone.',
    invalidDate: 'The date is not recognised. Try the YYYY-MM-DD HH:MM format.',
    useNow: 'Use now',
  },
} satisfies Record<Locale, Record<string, string>>;
