import type { Locale } from '../types';
import type { CaseId } from './logic';

export const strings = {
  es: {
    mode: 'Modo',
    input: 'Texto',
    placeholder: 'Escribe o pega texto: una frase, identificadores o una lista de líneas',
    stats: 'Recuento',
    chars: 'Caracteres',
    words: 'Palabras',
    lines: 'Líneas',
    bytes: 'Bytes (UTF-8)',
    cases: 'Conversiones',
    emptyCases: 'Escribe algo y verás las diez conversiones a la vez.',
    perLine: 'Los estilos de código (camelCase, snake_case…) convierten cada línea por separado.',
    sort: 'Ordenar',
    sortNone: 'Sin ordenar',
    sortAz: 'A-Z',
    sortZa: 'Z-A',
    sortNatural: 'Natural (2 antes que 10)',
    reverse: 'Invertir el orden',
    dedupe: 'Quitar duplicadas',
    removeEmpty: 'Quitar vacías',
    trim: 'Recortar espacios',
    number: 'Numerar',
    result: 'Resultado',
    emptyLines: 'Escribe o pega varias líneas y elige qué hacer con ellas.',
    resultLines: '{n} líneas',
  },
  en: {
    mode: 'Mode',
    input: 'Text',
    placeholder: 'Type or paste text: a sentence, identifiers or a list of lines',
    stats: 'Count',
    chars: 'Characters',
    words: 'Words',
    lines: 'Lines',
    bytes: 'Bytes (UTF-8)',
    cases: 'Conversions',
    emptyCases: 'Type something to see all ten conversions at once.',
    perLine: 'Code styles (camelCase, snake_case…) convert each line on its own.',
    sort: 'Sort',
    sortNone: 'Unsorted',
    sortAz: 'A-Z',
    sortZa: 'Z-A',
    sortNatural: 'Natural (2 before 10)',
    reverse: 'Reverse order',
    dedupe: 'Remove duplicates',
    removeEmpty: 'Remove empty',
    trim: 'Trim spaces',
    number: 'Number',
    result: 'Result',
    emptyLines: 'Type or paste several lines and choose what to do with them.',
    resultLines: '{n} lines',
  },
} satisfies Record<Locale, Record<string, string>>;

/** Display names for the prose cases. Code styles (camelCase, snake_case…) keep the label from CASES. */
export const caseNames: Record<Locale, Partial<Record<CaseId, string>>> = {
  es: { upper: 'MAYÚSCULAS', lower: 'minúsculas', title: 'Tipo Título', sentence: 'Tipo oración' },
  en: { upper: 'UPPER CASE', lower: 'lower case', title: 'Title Case', sentence: 'Sentence case' },
};
