import type { Locale } from '../types';

export const strings = {
  es: {
    picker: 'Selector de color',
    preview: 'Muestra',
    hex: 'HEX',
    rgb: 'RGB',
    hsl: 'HSL',
    oklch: 'OKLCH',
    invalidHex: 'Escribe 3 o 6 cifras hexadecimales, como #58a6ff o #5af.',
    invalidRgb: 'Escribe tres valores de 0 a 255, como rgb(88, 166, 255).',
    invalidHsl:
      'Escribe tono (0–360), saturación y luminosidad (0–100 %), como hsl(213, 100%, 67%).',
    invalidOklch: 'Escribe L (0–100 %), C (0–0,4) y H (0–360), como oklch(70% 0.15 250).',
    outOfGamut: 'Ese color OKLCH queda fuera de sRGB: se ha ajustado al más cercano.',
    contrast: 'Contraste WCAG',
    onWhite: 'Sobre blanco',
    onBlack: 'Sobre negro',
    ratio: 'Contraste {r}:1',
    normal: 'Texto normal',
    large: 'Texto grande',
    fail: 'No pasa',
    sample: 'Texto de ejemplo',
  },
  en: {
    picker: 'Color picker',
    preview: 'Swatch',
    hex: 'HEX',
    rgb: 'RGB',
    hsl: 'HSL',
    oklch: 'OKLCH',
    invalidHex: 'Type 3 or 6 hex digits, like #58a6ff or #5af.',
    invalidRgb: 'Type three values from 0 to 255, like rgb(88, 166, 255).',
    invalidHsl: 'Type hue (0–360), saturation and lightness (0–100%), like hsl(213, 100%, 67%).',
    invalidOklch: 'Type L (0–100%), C (0–0.4) and H (0–360), like oklch(70% 0.15 250).',
    outOfGamut: 'That OKLCH color is outside sRGB: it was adjusted to the closest one.',
    contrast: 'WCAG contrast',
    onWhite: 'On white',
    onBlack: 'On black',
    ratio: 'Contrast {r}:1',
    normal: 'Normal text',
    large: 'Large text',
    fail: 'Fails',
    sample: 'Sample text',
  },
} satisfies Record<Locale, Record<string, string>>;
