import type { Locale } from '../types';
import type { Quantity } from './logic';

export const strings = {
  es: {
    tabs: 'Magnitud',
    value: 'Valor',
    from: 'Unidad',
    result: 'Equivalencias',
    empty: 'Escribe un valor para verlo en todas las unidades.',
    invalid: 'Escribe un número, por ejemplo 1234,5.',
    belowAbsoluteZero: 'Está por debajo del cero absoluto (−273,15 °C).',
    copyUnit: 'Copiar en {u}',
  },
  en: {
    tabs: 'Quantity',
    value: 'Value',
    from: 'Unit',
    result: 'Equivalents',
    empty: 'Type a value to see it in every unit.',
    invalid: 'Type a number, for example 1234.5.',
    belowAbsoluteZero: 'That is below absolute zero (−273.15 °C).',
    copyUnit: 'Copy in {u}',
  },
} satisfies Record<Locale, Record<string, string>>;

export const negativeMessages: Record<Locale, Record<Exclude<Quantity, 'temperature'>, string>> = {
  es: {
    length: 'Una longitud no puede ser negativa.',
    mass: 'Una masa no puede ser negativa.',
    volume: 'Un volumen no puede ser negativo.',
    area: 'Un área no puede ser negativa.',
    speed: 'Aquí la velocidad no puede ser negativa.',
    data: 'Una cantidad de datos no puede ser negativa.',
  },
  en: {
    length: 'A length cannot be negative.',
    mass: 'A mass cannot be negative.',
    volume: 'A volume cannot be negative.',
    area: 'An area cannot be negative.',
    speed: 'Speed cannot be negative here.',
    data: 'An amount of data cannot be negative.',
  },
};

export const unitNames: Record<Locale, Record<string, string>> = {
  es: {
    um: 'Micrómetro',
    mm: 'Milímetro',
    cm: 'Centímetro',
    m: 'Metro',
    km: 'Kilómetro',
    in: 'Pulgada',
    ft: 'Pie',
    yd: 'Yarda',
    mi: 'Milla',
    nmi: 'Milla náutica',
    mg: 'Miligramo',
    g: 'Gramo',
    kg: 'Kilogramo',
    t: 'Tonelada',
    oz: 'Onza',
    lb: 'Libra',
    st: 'Stone',
    C: 'Grado Celsius',
    F: 'Grado Fahrenheit',
    K: 'Kelvin',
    ml: 'Mililitro',
    cm3: 'Centímetro cúbico',
    cl: 'Centilitro',
    dl: 'Decilitro',
    l: 'Litro',
    m3: 'Metro cúbico',
    tsp: 'Cucharadita (EE. UU.)',
    tbsp: 'Cucharada (EE. UU.)',
    floz: 'Onza líquida (EE. UU.)',
    cup: 'Taza (EE. UU.)',
    pt: 'Pinta (EE. UU.)',
    qt: 'Cuarto de galón (EE. UU.)',
    gal: 'Galón (EE. UU.)',
    flozuk: 'Onza líquida (R. U.)',
    ptuk: 'Pinta (R. U.)',
    galuk: 'Galón (R. U.)',
    mm2: 'Milímetro cuadrado',
    cm2: 'Centímetro cuadrado',
    m2: 'Metro cuadrado',
    ha: 'Hectárea',
    km2: 'Kilómetro cuadrado',
    in2: 'Pulgada cuadrada',
    ft2: 'Pie cuadrado',
    yd2: 'Yarda cuadrada',
    ac: 'Acre',
    mi2: 'Milla cuadrada',
    mps: 'Metro por segundo',
    kmh: 'Kilómetro por hora',
    mph: 'Milla por hora',
    kn: 'Nudo',
    fps: 'Pie por segundo',
    bit: 'Bit',
    kbit: 'Kilobit',
    Mbit: 'Megabit',
    Gbit: 'Gigabit',
    B: 'Byte',
    kB: 'Kilobyte',
    MB: 'Megabyte',
    GB: 'Gigabyte',
    TB: 'Terabyte',
    KiB: 'Kibibyte',
    MiB: 'Mebibyte',
    GiB: 'Gibibyte',
    TiB: 'Tebibyte',
  },
  en: {
    um: 'Micrometer',
    mm: 'Millimeter',
    cm: 'Centimeter',
    m: 'Meter',
    km: 'Kilometer',
    in: 'Inch',
    ft: 'Foot',
    yd: 'Yard',
    mi: 'Mile',
    nmi: 'Nautical mile',
    mg: 'Milligram',
    g: 'Gram',
    kg: 'Kilogram',
    t: 'Metric ton',
    oz: 'Ounce',
    lb: 'Pound',
    st: 'Stone',
    C: 'Degree Celsius',
    F: 'Degree Fahrenheit',
    K: 'Kelvin',
    ml: 'Milliliter',
    cm3: 'Cubic centimeter',
    cl: 'Centiliter',
    dl: 'Deciliter',
    l: 'Liter',
    m3: 'Cubic meter',
    tsp: 'Teaspoon (US)',
    tbsp: 'Tablespoon (US)',
    floz: 'Fluid ounce (US)',
    cup: 'Cup (US)',
    pt: 'Pint (US)',
    qt: 'Quart (US)',
    gal: 'Gallon (US)',
    flozuk: 'Fluid ounce (UK)',
    ptuk: 'Pint (UK)',
    galuk: 'Gallon (UK)',
    mm2: 'Square millimeter',
    cm2: 'Square centimeter',
    m2: 'Square meter',
    ha: 'Hectare',
    km2: 'Square kilometer',
    in2: 'Square inch',
    ft2: 'Square foot',
    yd2: 'Square yard',
    ac: 'Acre',
    mi2: 'Square mile',
    mps: 'Meter per second',
    kmh: 'Kilometer per hour',
    mph: 'Mile per hour',
    kn: 'Knot',
    fps: 'Foot per second',
    bit: 'Bit',
    kbit: 'Kilobit',
    Mbit: 'Megabit',
    Gbit: 'Gigabit',
    B: 'Byte',
    kB: 'Kilobyte',
    MB: 'Megabyte',
    GB: 'Gigabyte',
    TB: 'Terabyte',
    KiB: 'Kibibyte',
    MiB: 'Mebibyte',
    GiB: 'Gibibyte',
    TiB: 'Tebibyte',
  },
};
