import type { Locale } from '../types';

export const strings = {
  es: {
    amount: 'Importe',
    direction: 'El importe es',
    base: 'Base imponible',
    net: 'Líquido a cobrar',
    irpf: 'Retención de IRPF',
    irpf15: '15 % (general)',
    irpf7: '7 % (inicio de actividad)',
    irpf19: '19 % (alquileres y capital)',
    other: 'Otro',
    otherRate: 'Retención (%)',
    vat: 'IVA',
    vat0: '0 % (exento)',
    result: 'Factura',
    plusVat: '+ IVA ({r} %)',
    minusIrpf: '− Retención IRPF ({r} %)',
    total: 'Total a cobrar',
    note: 'La retención la ingresa tu cliente en Hacienda a cuenta de tu IRPF.',
    disclaimer:
      'Cálculo orientativo; no es asesoramiento fiscal. Comprueba el tipo que te corresponde.',
    inexact: 'Ninguna base da exactamente {target}; la más cercana da {got}.',
    invalid: 'Escribe un número, por ejemplo 1234,5.',
    rateInvalid: 'Escribe un porcentaje de 0 a 100, por ejemplo 15.',
    impossible: 'Con estos tipos no hay ninguna base posible: baja la retención.',
    copy: 'Copiar el desglose',
  },
  en: {
    amount: 'Amount',
    direction: 'The amount is',
    base: 'Net amount (base)',
    net: 'Amount to be paid',
    irpf: 'IRPF withholding',
    irpf15: '15% (standard)',
    irpf7: '7% (new activity)',
    irpf19: '19% (rentals and capital)',
    other: 'Other',
    otherRate: 'Withholding (%)',
    vat: 'VAT',
    vat0: '0% (exempt)',
    result: 'Invoice',
    plusVat: '+ VAT ({r}%)',
    minusIrpf: '− IRPF withholding ({r}%)',
    total: 'Total to be paid',
    note: 'Your client pays the withholding to the Tax Agency on account of your income tax.',
    disclaimer: 'An estimate, not tax advice. Check which rate applies to you.',
    inexact: 'No base gives exactly {target}; the closest gives {got}.',
    invalid: 'Type a number, for example 1234.5.',
    rateInvalid: 'Type a percentage from 0 to 100, for example 15.',
    impossible: 'No base is possible with these rates: lower the withholding.',
    copy: 'Copy the breakdown',
  },
} satisfies Record<Locale, Record<string, string>>;
