import type { Locale } from '../types';

export const strings = {
  es: {
    mode: 'Modo',
    input: 'Texto o Base64',
    placeholder: 'Escribe texto para codificarlo o pega Base64 para decodificarlo',
    urlSafe: 'URL-safe (- y _, sin =)',
    result: 'Resultado',
    encoded: 'Codificado: texto → Base64',
    decoded: 'Decodificado: Base64 → texto',
    errorInvalid: 'No es Base64 válido',
    errorInvalidHint:
      'Base64 solo usa letras, números, + y / (o - y _), con = al final. Revisa que no falte ni sobre ningún carácter.',
    errorBinary: 'Es Base64, pero no contiene texto',
    errorBinaryHint:
      'Parece un archivo (una imagen, un PDF…). Pégalo en la pestaña Archivo para descargarlo.',
    empty: 'Escribe o pega algo y el resultado aparecerá aquí.',
    fileToBase64: 'Archivo → Base64',
    fileName: 'Nombre',
    fileType: 'Tipo',
    fileSize: 'Tamaño',
    copyDataUri: 'Copiar data URI',
    copyBase64: 'Copiar Base64',
    tooBig: 'El archivo supera {max}. Para archivos tan grandes usa la línea de comandos (base64).',
    base64ToFile: 'Base64 → archivo',
    payload: 'Base64 o data URI',
    payloadPlaceholder: 'data:image/png;base64,iVBORw0KGgo…',
    payloadInvalid: 'No es Base64 válido. Si es un data URI, comprueba que incluye «;base64,».',
    payloadEmpty: 'Pega Base64 o un data URI para descargarlo como archivo.',
    detectedType: 'Tipo detectado',
    unknownType: 'desconocido',
    downloadFile: 'Descargar archivo',
    preview: 'Vista previa',
    filePrefix: 'archivo',
  },
  en: {
    mode: 'Mode',
    input: 'Text or Base64',
    placeholder: 'Type text to encode it or paste Base64 to decode it',
    urlSafe: 'URL-safe (- and _, no =)',
    result: 'Result',
    encoded: 'Encoded: text → Base64',
    decoded: 'Decoded: Base64 → text',
    errorInvalid: 'Not valid Base64',
    errorInvalidHint:
      'Base64 only uses letters, digits, + and / (or - and _), with = at the end. Check that no character is missing or extra.',
    errorBinary: 'It is Base64, but not text',
    errorBinaryHint:
      'It looks like a file (an image, a PDF…). Paste it in the File tab to download it.',
    empty: 'Type or paste something and the result will appear here.',
    fileToBase64: 'File → Base64',
    fileName: 'Name',
    fileType: 'Type',
    fileSize: 'Size',
    copyDataUri: 'Copy data URI',
    copyBase64: 'Copy Base64',
    tooBig: 'The file is larger than {max}. For files that big, use the command line (base64).',
    base64ToFile: 'Base64 → file',
    payload: 'Base64 or data URI',
    payloadPlaceholder: 'data:image/png;base64,iVBORw0KGgo…',
    payloadInvalid: 'Not valid Base64. If it is a data URI, check that it includes “;base64,”.',
    payloadEmpty: 'Paste Base64 or a data URI to download it as a file.',
    detectedType: 'Detected type',
    unknownType: 'unknown',
    downloadFile: 'Download file',
    preview: 'Preview',
    filePrefix: 'file',
  },
} satisfies Record<Locale, Record<string, string>>;
