import type { Locale } from '../types';

export const strings = {
  es: {
    original: 'Original',
    modified: 'Modificado',
    originalPlaceholder: '{"nombre": "Ana", "edad": 34}',
    modifiedPlaceholder: '{"edad": 35, "nombre": "Ana", "ciudad": "Madrid"}',
    jsonError: 'JSON no válido en la línea {line}, columna {column}',
    jsonErrorNoLine: 'El JSON no es válido',
    filter: 'Mostrar',
    all: 'Todas',
    added: 'Añadidas',
    removed: 'Eliminadas',
    changed: 'Cambiadas',
    addedOne: '{n} añadida',
    addedMany: '{n} añadidas',
    removedOne: '{n} eliminada',
    removedMany: '{n} eliminadas',
    changedOne: '{n} cambiada',
    changedMany: '{n} cambiadas',
    kindAdded: 'añadida',
    kindRemoved: 'eliminada',
    kindChanged: 'cambiada',
    result: 'Diferencias',
    equal: 'Los dos JSON son equivalentes (el orden de las claves no importa)',
    empty: 'Pega los dos JSON y aquí verás qué cambia.',
    waiting: 'Falta el otro JSON.',
    arrays: 'En las listas, el orden importa: se comparan posición a posición.',
    more: '… y {n} más',
    noneOfKind: 'No hay diferencias de este tipo.',
    copyReport: 'Copiar informe',
    swap: 'Intercambiar',
  },
  en: {
    original: 'Original',
    modified: 'Modified',
    originalPlaceholder: '{"name": "Ana", "age": 34}',
    modifiedPlaceholder: '{"age": 35, "name": "Ana", "city": "Madrid"}',
    jsonError: 'Invalid JSON at line {line}, column {column}',
    jsonErrorNoLine: 'The JSON is not valid',
    filter: 'Show',
    all: 'All',
    added: 'Added',
    removed: 'Removed',
    changed: 'Changed',
    addedOne: '{n} added',
    addedMany: '{n} added',
    removedOne: '{n} removed',
    removedMany: '{n} removed',
    changedOne: '{n} changed',
    changedMany: '{n} changed',
    kindAdded: 'added',
    kindRemoved: 'removed',
    kindChanged: 'changed',
    result: 'Differences',
    equal: 'Both JSON documents are equivalent (key order does not matter)',
    empty: 'Paste both JSON documents and you will see what changes here.',
    waiting: 'The other JSON is missing.',
    arrays: 'In lists order matters: they are compared position by position.',
    more: '… and {n} more',
    noneOfKind: 'No differences of this kind.',
    copyReport: 'Copy report',
    swap: 'Swap',
  },
} satisfies Record<Locale, Record<string, string>>;
