import type { Locale } from '../types';

export const strings = {
  es: {
    mode: 'Modo',
    input: 'Texto',
    placeholder: 'Escribe o pega el texto que quieres resumir',
    notStored: 'Lo que escribes aquí no se guarda.',
    uppercase: 'Mayúsculas',
    compare: 'Comparar con',
    comparePlaceholder: 'Pega el hash esperado (de cualquiera de los cinco algoritmos)',
    matches: 'Coincide con {algo}',
    noMatch: 'No coincide con ninguno',
    noMatchHint: 'Comprueba que es el mismo texto, sin espacios ni saltos de línea de más.',
    result: 'Hashes',
    empty: 'Escribe algo y verás sus cinco hashes al momento.',
    fileEmpty: 'Elige un archivo y verás sus cinco hashes.',
    reading: 'Calculando…',
    file: 'Archivo',
    fileError: 'No se pudo leer el archivo. Prueba de nuevo o con otro archivo.',
    tooBig: 'El archivo supera {max}. Para archivos tan grandes usa sha256sum o certutil.',
    copyMain: 'Copiar SHA-256',
  },
  en: {
    mode: 'Mode',
    input: 'Text',
    placeholder: 'Type or paste the text you want to hash',
    notStored: 'What you type here is not stored.',
    uppercase: 'Uppercase',
    compare: 'Compare with',
    comparePlaceholder: 'Paste the expected hash (from any of the five algorithms)',
    matches: 'Matches {algo}',
    noMatch: 'Does not match any',
    noMatchHint: 'Check that it is the same text, with no extra spaces or line breaks.',
    result: 'Hashes',
    empty: 'Type something to see its five hashes right away.',
    fileEmpty: 'Choose a file to see its five hashes.',
    reading: 'Computing…',
    file: 'File',
    fileError: 'Could not read the file. Try again or use another file.',
    tooBig: 'The file is larger than {max}. For files that big, use sha256sum or certutil.',
    copyMain: 'Copy SHA-256',
  },
} satisfies Record<Locale, Record<string, string>>;
