import {
  ArrowLeftRight,
  Binary,
  BookOpen,
  Braces,
  CaseSensitive,
  Check,
  ChevronDown,
  ChevronRight,
  Clock,
  Code,
  CodeXml,
  Copy,
  Dices,
  Diff,
  FileCode,
  Fingerprint,
  Hash,
  House,
  IdCard,
  KeyRound,
  Keyboard,
  Link,
  Menu,
  Moon,
  Palette,
  PanelLeftClose,
  PanelLeftOpen,
  Pilcrow,
  RefreshCw,
  Regex,
  Search,
  Sparkles,
  Star,
  Sun,
  SquareTerminal,
  TriangleAlert,
  X,
} from '@lucide/svelte';
import type { IconName } from './icon-names';

export type { IconName } from './icon-names';

// Record<IconName, …> makes `pnpm check` fail if a name has no component or vice versa.
export const icons: Record<IconName, typeof House> = {
  'arrow-left-right': ArrowLeftRight,
  binary: Binary,
  'book-open': BookOpen,
  braces: Braces,
  'case-sensitive': CaseSensitive,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  clock: Clock,
  code: Code,
  'code-xml': CodeXml,
  copy: Copy,
  dices: Dices,
  diff: Diff,
  'file-code': FileCode,
  fingerprint: Fingerprint,
  hash: Hash,
  house: House,
  'id-card': IdCard,
  'key-round': KeyRound,
  keyboard: Keyboard,
  link: Link,
  menu: Menu,
  moon: Moon,
  palette: Palette,
  'panel-left-close': PanelLeftClose,
  'panel-left-open': PanelLeftOpen,
  pilcrow: Pilcrow,
  'refresh-cw': RefreshCw,
  regex: Regex,
  search: Search,
  sparkles: Sparkles,
  star: Star,
  sun: Sun,
  terminal: SquareTerminal,
  'triangle-alert': TriangleAlert,
  x: X,
};
