import {
  ArrowDownUp,
  ArrowLeftRight,
  Barcode,
  Binary,
  BookOpen,
  Braces,
  Building,
  Calculator,
  CalendarClock,
  CalendarDays,
  Car,
  CaseSensitive,
  Check,
  ChevronDown,
  ChevronRight,
  Clock,
  Code,
  CodeXml,
  Coins,
  Copy,
  CreditCard,
  Database,
  Dice5,
  Dices,
  Diff,
  Divide,
  FerrisWheel,
  FileBraces,
  FileCode,
  FileText,
  Fingerprint,
  GitCompareArrows,
  Globe,
  HardDrive,
  Hash,
  HeartPulse,
  House,
  IdCard,
  IdCardLanyard,
  KeyRound,
  Keyboard,
  Landmark,
  Link,
  Link2,
  Lock,
  LockKeyhole,
  MapPin,
  Menu,
  MonitorSmartphone,
  Moon,
  Network,
  Palette,
  PanelLeftClose,
  PanelLeftOpen,
  Percent,
  Phone,
  Pilcrow,
  QrCode,
  Receipt,
  ReceiptText,
  RefreshCw,
  Regex,
  Ruler,
  Scaling,
  Search,
  Server,
  Sheet,
  Shuffle,
  Sparkles,
  SquareTerminal,
  Star,
  Sun,
  Tag,
  TriangleAlert,
  Users,
  X,
} from '@lucide/svelte';
import type { IconName } from './icon-names';

export type { IconName } from './icon-names';

// Record<IconName, …> makes `pnpm check` fail if a name has no component or vice versa.
export const icons: Record<IconName, typeof House> = {
  'arrow-down-up': ArrowDownUp,
  'arrow-left-right': ArrowLeftRight,
  barcode: Barcode,
  binary: Binary,
  'book-open': BookOpen,
  braces: Braces,
  building: Building,
  calculator: Calculator,
  'calendar-clock': CalendarClock,
  'calendar-days': CalendarDays,
  car: Car,
  'case-sensitive': CaseSensitive,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  clock: Clock,
  code: Code,
  'code-xml': CodeXml,
  coins: Coins,
  copy: Copy,
  'credit-card': CreditCard,
  database: Database,
  'dice-5': Dice5,
  dices: Dices,
  diff: Diff,
  divide: Divide,
  'ferris-wheel': FerrisWheel,
  'file-braces': FileBraces,
  'file-code': FileCode,
  'file-text': FileText,
  fingerprint: Fingerprint,
  'git-compare-arrows': GitCompareArrows,
  globe: Globe,
  'hard-drive': HardDrive,
  hash: Hash,
  'heart-pulse': HeartPulse,
  house: House,
  'id-card': IdCard,
  'id-card-lanyard': IdCardLanyard,
  'key-round': KeyRound,
  keyboard: Keyboard,
  landmark: Landmark,
  link: Link,
  'link-2': Link2,
  lock: Lock,
  'lock-keyhole': LockKeyhole,
  'map-pin': MapPin,
  menu: Menu,
  'monitor-smartphone': MonitorSmartphone,
  moon: Moon,
  network: Network,
  palette: Palette,
  'panel-left-close': PanelLeftClose,
  'panel-left-open': PanelLeftOpen,
  percent: Percent,
  phone: Phone,
  pilcrow: Pilcrow,
  'qr-code': QrCode,
  receipt: Receipt,
  'receipt-text': ReceiptText,
  'refresh-cw': RefreshCw,
  regex: Regex,
  ruler: Ruler,
  scaling: Scaling,
  search: Search,
  server: Server,
  sheet: Sheet,
  shuffle: Shuffle,
  sparkles: Sparkles,
  star: Star,
  sun: Sun,
  tag: Tag,
  terminal: SquareTerminal,
  'triangle-alert': TriangleAlert,
  users: Users,
  x: X,
};
