import {
  ArrowLeftRight,
  BookOpen,
  Braces,
  Check,
  ChevronDown,
  ChevronRight,
  Code,
  Copy,
  Dices,
  Fingerprint,
  House,
  IdCard,
  Keyboard,
  Menu,
  Moon,
  PanelLeftClose,
  PanelLeftOpen,
  RefreshCw,
  Search,
  Sparkles,
  Star,
  Sun,
  SquareTerminal,
  X,
} from '@lucide/svelte';
import type { IconName } from './icon-names';

export type { IconName } from './icon-names';

// Record<IconName, …> makes `pnpm check` fail if a name has no component or vice versa.
export const icons: Record<IconName, typeof House> = {
  'arrow-left-right': ArrowLeftRight,
  'book-open': BookOpen,
  braces: Braces,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  code: Code,
  copy: Copy,
  dices: Dices,
  fingerprint: Fingerprint,
  house: House,
  'id-card': IdCard,
  keyboard: Keyboard,
  menu: Menu,
  moon: Moon,
  'panel-left-close': PanelLeftClose,
  'panel-left-open': PanelLeftOpen,
  'refresh-cw': RefreshCw,
  search: Search,
  sparkles: Sparkles,
  star: Star,
  sun: Sun,
  terminal: SquareTerminal,
  x: X,
};
