export const ICON_NAMES = [
  'arrow-left-right',
  'binary',
  'book-open',
  'braces',
  'case-sensitive',
  'check',
  'chevron-down',
  'chevron-right',
  'clock',
  'code',
  'code-xml',
  'copy',
  'dices',
  'diff',
  'file-code',
  'fingerprint',
  'hash',
  'house',
  'id-card',
  'key-round',
  'keyboard',
  'link',
  'menu',
  'moon',
  'palette',
  'panel-left-close',
  'panel-left-open',
  'pilcrow',
  'refresh-cw',
  'regex',
  'search',
  'sparkles',
  'star',
  'sun',
  'terminal',
  'triangle-alert',
  'x',
] as const;

export type IconName = (typeof ICON_NAMES)[number];
